domain: cornell-tech-airlab.github.io
url: https://cornell-tech-airlab.github.io
baseurl: "/cornell2025.nerc.io"

# Site settings
title: NERC 2025
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Tapomayukh Bhattacharjee 
  pic: 1
  position: General Chair
  level: Assistant Professor
  department: Computer Science
  university: Cornell University

- name: Cara M. Nunez
  pic: 2
  position: Program Chair
  level: Assistant Professor
  department: Mechanical and Aerospace 
  university: Cornell University

- name: Elizabeth Farrell Helbling
  pic: 3
  position: Local and Publications Chair
  level: Assistant Professor
  department: Electrical and Computer Engineering  
  university: Cornell University

people2:
- name: Shiqi Zhang
  pic: 4
  position: Registration Chair 
  level: Associate Professor 
  department: Computer Science
  university: Binghamton University

- name: Angelique Taylor
  pic: 5
  position: Website Chair
  level: Assistant Professor
  department: Information Science
  university: Cornell University
  website: https://airlab.cis.cornell.edu/

- name: Kuan Fang
  pic: 6
  position: Sponsorship Chair 
  level: Assistant Professor
  department: Computer Science
  university: Cornell University

people3:
- name: Preston Culbertson
  pic: 7
  position: Publicity Chair
  level: Assistant Professor
  department: Computer Science
  university: Cornell University

- name: Elizabeth Eastabook
  pic: 8
  position: Director of Administration
  level: #
  department: Computer Science
  university: Cornell University

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 127 Hoy Road
  - line: Ithaca, NY 14853

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed
