domain: cornell-tech-airlab.github.io
url: https://cornell-tech-airlab.github.io
baseurl: "/cornell2025.nerc.io"

# Site settings
title: NERC 2025
email: nerc2025.cornell@gmail.com
description: "We are pleased to announce that the Northeast Robotics Colloquium (NERC) 2025 will be hosted by Cornell University on Saturday, October 11, 2025. NERC 2025 will provide a vibrant forum for researchers, students, and industry professionals in the field of robotics. The colloquium will feature distinguished keynotes, rising star lightning talks, engaging poster sessions, valuable networking opportunities, and technical demonstrations."


# Team names, titles and social links
people:
- name: Tapomayukh Bhattacharjee 
  pic: 1
  position: General Chair
  level: Assistant Professor
  department: Computer Science
  university: Cornell University
  website: https://sites.google.com/site/tapomayukh

- name: Cara M. Nunez
  pic: 2
  position: Program Chair
  level: Assistant Professor
  department: Mechanical and Aerospace 
  university: Cornell University
  website: https://www.engineering.cornell.edu/people/cara-m-nunez/

- name: Elizabeth Farrell Helbling
  pic: 3
  position: Publications Chair
  level: Assistant Professor
  department: Electrical and Computer Engineering  
  university: Cornell University
  website: https://www.engineering.cornell.edu/people/elizabeth-farrell-helbling/

people2:
- name: Shiqi Zhang
  pic: 4
  position: Registration Chair 
  level: Associate Professor 
  department: Computer Science
  university: Binghamton University
  website: https://www.binghamton.edu/computer-science/people/profile.html?id=zhangs

- name: Angelique Taylor
  pic: 5
  position: Website Chair
  level: Assistant Professor
  department: Information Science
  university: Cornell University
  website: https://airlab.cis.cornell.edu/

- name: Kuan Fang
  pic: 6
  position: Sponsorship Chair 
  level: Assistant Professor
  department: Computer Science
  university: Cornell University
  website: https://kuanfang.github.io/

people3:
- name: Preston Culbertson
  pic: 7
  position: Publicity Chair
  level: Assistant Professor
  department: Computer Science
  university: Cornell University
  website: https://pculbertson.github.io/

- name: Elizabeth Eastabook
  pic: 8
  position: Director of Administration
  level: #
  department: Computer Science
  university: Cornell University
  website: https://www.cs.cornell.edu/people/staff

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/NERC_Robotics
  - title: bluesky
    url: https://bsky.app/profile/nerc-robotics.bsky.social
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket 
  #  url: http://bitbucket.org/jekyll
  #- title: github
  #  url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 127 Hoy Road
  - line: Ithaca, NY 14853

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed
